import PDFDocument from 'pdfkit';
import { db } from '../db/database.js';
import * as d3 from 'd3';
import { JSDOM } from 'jsdom';
import SVGtoPDF from 'svg-to-pdfkit';

class ReportGenerator {
    async generateReport(emissionData, options = {}) {
        return new Promise(async (resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50, size: 'A4' });
                const buffers = [];

                doc.on('data', buffers.push.bind(buffers));
                doc.on('end', () => resolve(Buffer.concat(buffers)));

                const companyName = options.companyName || 'Unknown Company';
                const reportingPeriod = options.reportingPeriod || new Date().toISOString().slice(0, 7);
                const framework = options.framework || 'CSRD & SEC Aligned';

                // History for YoY Comparison
                const history = await db.getSnapshots(2);
                let previousTotal = null;
                if (history.length > 1) {
                    previousTotal = history[1].total;
                }

                // Title Page
                this._addHeader(doc, companyName, reportingPeriod, framework);

                // Executive Summary
                this._addExecutiveSummary(doc, emissionData.totals, previousTotal);

                // Charts
                await this._addCharts(doc, emissionData);

                // Scope Breakdown
                this._addScopeBreakdown(doc, emissionData);

                // Vertical-Specific Sections (e.g., CSRD Transport Annex)
                if (options.vertical && options.vertical.report_templates) {
                    this._addVerticalSections(doc, emissionData, options.vertical);
                }

                // Footer
                this._addFooter(doc);

                doc.end();
            } catch (err) {
                reject(err);
            }
        });
    }

    _addHeader(doc, companyName, reportingPeriod, framework) {
        doc.rect(0, 0, doc.page.width, 100).fill('#0f172a');
        doc.fillColor('#ffffff')
            .fontSize(24)
            .text('Carbon Emissions Audit Report', 50, 40)
            .fontSize(10)
            .fillColor('#94a3b8')
            .text(`Generated by CarbonLens Autonomous ESG Agent | Framework: ${framework}`, 50, 70)
            .text(`Company: ${companyName} | Period: ${reportingPeriod}`, { align: 'right', lineGap: -10 })
            .moveDown(4);
    }

    _addExecutiveSummary(doc, totals, previousTotal) {
        doc.fillColor('#0f172a').fontSize(16).text('Executive Summary', 50, 130).moveDown(0.5);

        doc.fontSize(11).fillColor('#334155')
            .text('This autonomous report provides a comprehensive overview of greenhouse gas (GHG) emissions calculated in accordance with the GHG Protocol corporate standard. Data was ingested via MCP integrations from enterprise ERP and CRM systems, categorized using Gemini AI, and monitored for deviations.')
            .moveDown(1);

        // Summary Box
        doc.rect(50, doc.y, 495, 80).fillAndStroke('#f8fafc', '#e2e8f0');

        doc.fillColor('#0f172a').fontSize(12).text('Total Carbon Footprint', 70, doc.y - 65);
        doc.fontSize(24).fillColor('#3b82f6').text(`${Math.round(totals.total).toLocaleString()} kg CO2e`, 70, doc.y + 5);

        if (previousTotal !== null && previousTotal > 0) {
            const change = ((totals.total - previousTotal) / previousTotal) * 100;
            const color = change > 0 ? '#ef4444' : '#10b981';
            const text = change > 0 ? `▲ +${change.toFixed(1)}% vs previous period` : `▼ ${change.toFixed(1)}% vs previous period`;
            doc.fontSize(10).fillColor(color).text(text, 70, doc.y + 5);
        }

        doc.moveDown(4);
    }

    async _addCharts(doc, emissionData) {
        doc.fillColor('#0f172a').fontSize(16).text('Emissions by Scope', 50, doc.y).moveDown(1);

        const scopeData = [
            { name: 'Scope 1', value: emissionData.totals.scope1, color: '#f97316' },
            { name: 'Scope 2', value: emissionData.totals.scope2, color: '#3b82f6' },
            { name: 'Scope 3', value: emissionData.totals.scope3, color: '#10b981' }
        ].filter(d => d.value > 0);

        const svgString = this._generatePieChartSVG(scopeData, 300, 200);
        SVGtoPDF(doc, svgString, 150, doc.y, { width: 300, height: 200 });

        doc.moveDown(14);
    }

    _generatePieChartSVG(data, width, height) {
        const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>');
        const body = d3.select(dom.window.document.body);

        const radius = Math.min(width, height) / 2;

        const svg = body.append('svg')
            .attr('width', width)
            .attr('height', height)
            .attr('xmlns', 'http://www.w3.org/2000/svg');

        const g = svg.append('g')
            .attr('transform', `translate(${width / 2},${height / 2})`);

        const pie = d3.pie().value(d => d.value).sort(null);
        const arc = d3.arc().innerRadius(radius * 0.5).outerRadius(radius * 0.8);

        const arcs = g.selectAll('arc').data(pie(data)).enter().append('g');

        arcs.append('path')
            .attr('d', arc)
            .attr('fill', d => d.data.color)
            .attr('stroke', '#ffffff')
            .attr('stroke-width', '2px');

        arcs.append('text')
            .attr('transform', d => `translate(${arc.centroid(d)})`)
            .attr('text-anchor', 'middle')
            .style('font-family', 'sans-serif')
            .style('font-size', '10px')
            .style('fill', '#ffffff')
            .text(d => `${Math.round((d.data.value / d3.sum(data, v => v.value)) * 100)}%`);

        // Legend
        const legend = svg.append('g').attr('transform', `translate(${width - 80}, 20)`);
        const legendItems = legend.selectAll('g').data(data).enter().append('g')
            .attr('transform', (d, i) => `translate(0, ${i * 20})`);

        legendItems.append('rect')
            .attr('width', 12).attr('height', 12)
            .attr('fill', d => d.color);

        legendItems.append('text')
            .attr('x', 20).attr('y', 10)
            .style('font-family', 'sans-serif').style('font-size', '12px').style('fill', '#334155')
            .text(d => d.name);

        return body.html();
    }

    _addScopeBreakdown(doc, emissionData) {
        doc.addPage();
        doc.fillColor('#0f172a').fontSize(16).text('Detailed Breakdown', 50, 50).moveDown(1);

        const formatScope = (title, items, total, color) => {
            doc.fillColor(color).fontSize(14).text(`${title} (${Math.round(total).toLocaleString()} kg CO2e)`);
            doc.moveDown(0.5);

            if (items.length === 0) {
                doc.fontSize(10).fillColor('#94a3b8').text('No data recorded for this scope.').moveDown(1);
                return;
            }

            const startX = 50;
            let startY = doc.y;

            doc.fontSize(10).fillColor('#64748b');
            doc.text('Category', startX, startY, { width: 120 });
            doc.text('Source', startX + 130, startY, { width: 180 });
            doc.text('Quantity', startX + 320, startY, { width: 70, align: 'right' });
            doc.text('Emissions (kg)', startX + 400, startY, { width: 95, align: 'right' });

            doc.moveTo(startX, startY + 12).lineTo(startX + 495, startY + 12).stroke('#e2e8f0');
            startY += 18;

            doc.fillColor('#334155');
            for (const item of items) {
                if (startY > doc.page.height - 100) {
                    doc.addPage();
                    startY = 50;
                }

                doc.text(item.category, startX, startY, { width: 120 });
                const sourceDesc = item.source.length > 30 ? item.source.slice(0, 27) + '...' : item.source;
                doc.text(sourceDesc, startX + 130, startY, { width: 180 });
                doc.text(`${item.activity_data} ${item.activity_unit}`, startX + 320, startY, { width: 70, align: 'right' });
                doc.text(Math.round(item.co2e_kg).toLocaleString(), startX + 400, startY, { width: 95, align: 'right' });

                doc.moveTo(startX, startY + 12).lineTo(startX + 495, startY + 12).stroke('#f1f5f9');
                startY += 18;
            }

            doc.y = startY + 10;
        };

        formatScope('Scope 1: Direct Emissions', emissionData.scope1, emissionData.totals.scope1, '#f97316');
        formatScope('Scope 2: Energy Indirect', emissionData.scope2, emissionData.totals.scope2, '#3b82f6');
        formatScope('Scope 3: Value Chain', emissionData.scope3, emissionData.totals.scope3, '#10b981');
    }

    _addVerticalSections(doc, emissionData, vertical) {
        if (!vertical.report_templates) return;

        for (const template of vertical.report_templates) {
            doc.addPage();
            doc.fillColor('#0f172a').fontSize(16).text(template.name, 50, 50).moveDown(1);

            doc.fontSize(10).fillColor('#334155')
                .text(`Industry-specific disclosure specialized for the ${vertical.label} vertical.`, { italic: true })
                .moveDown(1);

            if (template.id === 'csrd_transport_annex') {
                this._addTransportAnnex(doc, emissionData);
            } else {
                doc.text(template.description);
            }
        }
    }

    _addTransportAnnex(doc, emissionData) {
        doc.fontSize(12).fillColor('#0f172a').text('Freight & Logistics Performance Metrics').moveDown(0.5);

        const logisticsEntries = [...emissionData.scope1, ...emissionData.scope2, ...emissionData.scope3].filter(e =>
            e.category === 'Fuel Combustion' || e.category === 'Downstream Transport' || e.activity_type?.includes('freight')
        );

        const stats = logisticsEntries.reduce((acc, e) => {
            const type = e.activity_type || 'Other';
            if (!acc[type]) acc[type] = 0;
            acc[type] += e.co2e_kg;
            return acc;
        }, {});

        doc.fontSize(10).fillColor('#334155');
        doc.text('Performance by Transport Mode (kg CO2e):').moveDown(0.5);

        Object.entries(stats).forEach(([mode, value]) => {
            doc.text(`• ${mode}: ${Math.round(value).toLocaleString()} kg CO2e`, { indent: 20 });
        });

        doc.moveDown(1);
        doc.fontSize(11).text('Methodology Compliance:').moveDown(0.5);
        doc.fontSize(9).fillColor('#64748b').text(
            'In accordance with ESRS E1 and the GLEC Framework 3.0, these emissions reflect well-to-wheel (WTW) impacts where data quality allows. Logistics-specific emission factors from DEFRA 2024 have been applied to primary activity data.'
        );
    }

    _addFooter(doc) {
        const pages = doc.bufferedPageRange();
        for (let i = 0; i < pages.count; i++) {
            doc.switchToPage(i);
            doc.fontSize(8)
                .fillColor('#94a3b8')
                .text(`Page ${i + 1} of ${pages.count}`, 0, doc.page.height - 40, { align: 'center' })
                .text(new Date().toISOString(), 50, doc.page.height - 40, { align: 'left' });
        }
    }
}

export const reportGenerator = new ReportGenerator();
